src/index.css, src/index.js
Fixes #1.
Since the description field can be multiline and change the amount of space that rows occupies, the anchor is set on that field, rather than the name. An `anchor` CSS class has been added to add a top margin to compensate for the sticky header, otherwise the linked row would be hidden behind the header. This CSS fix is explained in this StackOverflow question: [sticky header internal links](https://stackoverflow.com/questions/7717894/sticky-header-internal-links)
=> BLD: added anchors to table rows

src/index.js
Fixes two linting error introduced in #3:
```
Line 214:8:  Anchors must have content and the content must be accessible by a screen reader
jsx-a11y/anchor-has-content
Line 214:8:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid,
navigable address as the href value. If you cannot provide an href, but still need the element to
resemble a link, use a button and change it with appropriate styles. Learn more: 
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md 
jsx-a11y/anchor-is-valid
```
These errors do not apply because we are setting an anchor with no `href` for internal linking purposes, so it has been addressed by way of ignoring the linting on that specific line.
=> BUG: fix lint error from #3

index.js
Now the viewBox of the treemap is equal to its width and height.
@lacabra kindly take a look at this PR
**Before**
**After**
Closes #10
=> Fix viewbox of distribution by SDG treemap

index.js
The problem was in iterations over sdg data. SDGs array contains [0-16] indexes so `sdgs[d['SDGNumber']]++;` failed in sdgs[17].
Fastest approach is to add 1 more cell in array so check in `102 line` do the rest.
I also fixed minor bug with displaying value in `14` sdg which doesn't fit both vertically and horizontally.
**Before**
**After**
@lacabra kindly check this PR. Do I need to change anything?
Closes #13
=> Fix displaying 17 sdg in Data visualization

generate_dpgs.js, generate_nominees.js
Complementary to unicef/publicgoods-candidates#535, propagates the folder renaming from `screening/` to `digitalpublicgoods/` and updates all references to screening.
=> MAINT: rename screening to dpgs

packages/eligibility/src/Eligibility.js, packages/eligibility/src/api/quizQuestions.js, packages/eligibility/src/components/Result.js
The pull request fixes #29.
- Takes correct answer as `No` in questions 4 and 6.
- If `Yes` is selected in questions 4 and 6, the user may be eligible if certain conditions are met.
Please note the following workflows:
- If 9/9 correct completely -> Page A (You are eligible)
- If at least 1 wrong completely and no maybes --> Page B (You are not eligible)
- If at least 1 wrong completely and at least 1 maybe --> Page B (Includes a "Furthermore" for the maybe question)
- If none wrong and at least 1 maybe --> Page C (You may be eligible given the conditions below)
=> Fix issue #29 and include "May be eligible" result

packages/eligibility/src/Eligibility.js
This fixes an important issue that was raised due to #34. 
The `debouncedSave()` function is not being called when the `Proceed` button is clicked. This also removes other warnings shown during the build.
=> Resolve issue in passing initial state 

packages/eligibility/README.md, packages/eligibility/src/components/Eligibility.js
Fix #49 
In order for CORS to work as intended, we have to use the same domain between both forms, that is `digitalpublicgoods.net`. Up until now, we were calling the form at `submission-digitalpublicgoods.vercel.app` which is on a different domain.
=> MAINT: updated submission form domain

packages/automation/generate_nominees.js
Fix #53 
- GitHub had changed its page layout, and so the crawler has been adjusted accordingly.
- An additional check has been implemented to validate whether we're "seeing" the chart. If not, it will error out so that we can catch it and make the necessary adjustments.
=> BUG: fix activity chart extraction

packages/eligibility/src/components/FAQ.js
Fix #57 by adding `key={index}` to each child in a list, and fix `className` property instead of `class` to match React nomenclature.
=> FIX #57: add key to list childs

packages/eligibility/src/api/quizQuestions.js, packages/eligibility/src/components/Eligibility.js, packages/eligibility/src/components/Result.js
Fix #51 
The following changes have been made in this pull request:
=> Update number of questions in Eligibility Form

packages/eligibility/src/components/FAQ.js, packages/eligibility/src/components/Result.js
Fix #59.
The error occurs because certain code is wrapped with `<p>...</p>` which then inserts HTML text from `src/api/quizQuestions` which also has `<p>...</p>` in it, thus triggering an error that `<p>` cannot be a descendant of `<p>`. To preserve the current structure, the outermost `<p>` is changed to a `<div>` that can have `<p>` as children.
Also addressing the following error in commit 2e1be7d
```
index.js:1 Warning: Failed prop type: Invalid prop `quizScore` of type `number` supplied to `Result`, expected `string`.
in Result (at Eligibility.js:348)
in Eligibility (at src/index.js:8)
```
=> FIX: #59 replace p with div

packages/registry/src/index.js
Fixes #69 by reorganizing the `types` array into a dictionary so that one can control how to display the text for each type (as in `aimodel` display name is `AI Model`) and refactors the manipulation of the prior types array as Object.keys(types) that returns an array of the keys, thereby maintaining the rest of the code intact).
=> BUG: add aimodel filter to registry

packages/map/pages/index.js
This PR bypass the limitation of github api by making multiple requests if the number of dpgs is more than 100.
I also fixed lint of the `renameCountry` object.
Kindly review the changes @lacabra 
Closes #73
=> [Map] Fix maximum load limitation of DPGs

packages/map/pages/index.js
Fixes an issue uncovered in #73 where the CI fails in pull_requests runs because it doesn't have access to env vars set up as secrets in this public repo for security reasons. The bug was in the code where it assumed that the request would always succeed. If we check whether the response has values or not addresses the issue without modifying the flow of the code.
Cc: @Rolikasi
=> BUG: fix CI with no env vars

packages/roadmap/src/components/Roadmap.js
Fix #76 by removing the `textLength` field. Luckily it has no effect on the other browsers that were displaying those fields correctly.
=> BUG: fix Firefox broken display of roadmap headers

packages/registry/src/index.js
Fix #78 by unchecking `nominees` in the corresponding filter side dialog, and calling the `handleChange()` at page load through `componentDidMount()` to reflect that setting. Tested successfully in localhost
=> BLD: fix #78

packages/automation/index.js
I found that the automation script keeps all `<script>`  files from previous versions of map. You can open [inspector ](https://digitalpublicgoods.net/map/) and find that there are more than 500 `<script>` nodes.
It ruins functionality of the map. Instead it supposed to keep in cycle only two `<script>` elements with ids `#dpga-libs-js` and `#dpga-main-js`.
This PR fixes that issue. Apologies that I didn't noticed that earlier.
@lacabra kindly review this PR. And I guess we need to rebuild digitalpublicgoods.net/map/ [index file](https://github.com/unicef/publicgoods-website/blob/main/map/index.html) from scratch to avoid errors.
=> [Map] fix automation script

packages/automation/generate_nominees.js
Propagates the changes introduced in DPGAlliance/publicgoods-candidates#924 where `repositoryURL` is replaced with array `repositories`  of objects containing properties `name` and `url`.
The logic checks first if properties `repositories` exist.
If it exists, checks if the array contains more than one item. If it does not, it will take the first item.
If it contains more than one item, it searches for the item named 'main'.
Cc: @nathanbaleeta
=> BUG: fix repositories array

packages/registry/src/index.js
Continues the work started in #96, In the first PR we modified the logic for how `nominees.json` is generated which is used to populate the registry. In this PR, we tackle the actual HTML code generation of the registry, accounting for the property name change. Local tests now indicate that the registry is finally restored.
Cc: @nathanbaleeta
=> BUG: fix processing of repositoryURL

packages/map/pages/index.js
Updated links to refer to `main` branch instead of `master` in `publicgoods-candidates`
=> MAINT: update branch master to main

packages/automation/generate_nominees.js
This PR fixes a bug first detected in the build of merging of DPGAlliance/publicgoods-candidates#958 triggered by an empty array in `repositories=[]`. The code to search for the repo should only run if these two conditionals are met:
- L146 `if(n.hasOwnProperty('repositories')){`
- L148 `if(n.repositories.length > 1) {`
Thus, the `match` and `fetchGithubActivity` are moved inside the last conditional above.
Please note that if either of the `if`s don't pass, `html` var defined in L145 is empty, and is assigned as an empty value in L161, which is the desired behavior
=> BUG: fix empty repo list

packages/registry/src/index.js
This PR fixes #131 and reveals a potential bug in the [generate_dpgs.js](https://github.com/DPGAlliance/publicgoods-scripts/blob/main/packages/automation/generate_dpgs.js) script. cc @lacabra 
Upon testing locally, I realized that the individual pages were not being properly generated because the [template used for the pages](https://github.com/DPGAlliance/publicgoods-website/blob/main/registry/index.html) did not have the word `Placeholder`.
this `Placeholder` keyword is what the code looks for to replace the content of the template.
Unless I am missing something, I would suggest that the template be fixed in the `publicgoods-website` repo by adding the `Placeholder` keyword before pushing this PR.
I have been wondering why this has not shown up earlier (again, unless I'm missing …
=> Updated project name url to point to DPG website

packages/registry/src/index.js
The first set of  DPGs put into the registry were hard coded. This was before a registry website. They do not conform to the current standard data structure. As such, they all point to one single blog post page listing them. This link to that post from the registry list was broken due to a previous PR.
=> fixed first DPGs registry link

packages/registry/src/index.js
In this PR:
- Visual HTML structure for the filters for Nominee & DPG have been removed.
- However, their functionality remains in `index.js` and forms part of how all the filters work.
- Refactoring would be done later to carefully remove them without breaking table filter functionality. It may also not be relevant to do so.
=> Removed HTML of Nominee-DPG filter

.gitignore, packages/automation/index.js
This PR:
- Refactors the Data Explorer section of the DPG website to point to the new review webapp's API.
- Removes mention of registry in the distribution chart output and Venn diagram
Note:
- Since the data is now pulling only DPG from the API instead of nominees like before, a few values in the chart may change from before either by increasing or decreasing.
ToDo:
- Alter the language of the registry page to remove mention of `nominees` in a number of the page's paragraphs.
=> Data explorer refactor

.github/workflows/auto.yml, packages/map/pages/index.js
One part of of the problem of currently failing builds is that the maps package is broken. 
This may be due to old legacy code and dependencies being updated or depricated. 
As such I am temporarily disabling it in the build to allowthe registry page to be compiled.
This means that links to the DPG map will return a 404 error.
=> HotFix: Temporarily removing map package

packages/community/index.html, packages/community/index.js, scripts/moveFiles.bash
This PR attempts to fix #175 
Since the DPG site is raw HTML based, it uses a very low-level solution of direct browser routing using vanilla JS.
=> Community redirect patch
