- generate_screened.js
This script scans the folder of `publicgoods-candidates/screening`, and for every `.json` file it finds in there, generates the corresponding page under https://digitalpublicgoods.net/registry
> BLD: automatic generation of screening projects (alpha)

- index.js
Finally did it! Main problem with d3 is that there is no one-line solution to add multiline text. I think that 2 lines of text and a value bellow look great, but 3 lines of text are too much.
Code bellow reproduce steps:
1) I created function that compares rect's and text's width. I found that `node.getComputedTextLength()` is the most efficient way to do it.
2) Try to fit full text into 1 line. If done we stop here
3) Try to fit text without value.
4) Split text into 2 perfect lines that will fit the container. Solution: iterate over text and move last words one by one to the second text line until both fit the container.
5) Push value to the last line.
**Before**
**After**
@lacabra kindly review this PR
Closes #9
> Improve distribution by SDG data visualization

- index.js
- src/index.css
Changed CSS mostly to adapt to new DPGA theme
> MAINT: adapted to new DPGA theme

- package-lock.json
- packages/eligibility/package-lock.json
- packages/eligibility/package.json
- packages/eligibility/src/Eligibility.js
- packages/eligibility/src/api/quizQuestions.js
- packages/eligibility/src/components/AnswerOption.js
- packages/eligibility/src/components/FAQ.js
- packages/eligibility/src/components/Question.js
- packages/eligibility/src/components/QuestionCount.js
- packages/eligibility/src/components/Quiz.js
- packages/eligibility/src/components/Result.js
- packages/eligibility/src/components/Summary.js
- packages/eligibility/src/index.css
> Add progress bar and keyboard shortcuts

- packages/eligibility/src/components/AnswerOption.js
- packages/eligibility/src/components/FAQ.js
- packages/eligibility/src/components/QuestionCount.js
- packages/eligibility/src/components/Summary.js
Fixed all warnings raised due to #26.
> Fix warnings 

- packages/automation/index.js
- packages/registry/src/index.css
Kindly review this PR. @nathanfletcher @lacabra 
Closes #27
> fix tooltip and label

- package-lock.json
- packages/eligibility/package-lock.json
- packages/eligibility/package.json
- packages/eligibility/src/Eligibility.js
- packages/eligibility/src/api/quizQuestions.js
Fix #24 
Pass the answers collected in the Eligibility form to the Submissions form.
> Pass initial state onto Submissions Form

- packages/eligibility/src/Eligibility.js
- packages/eligibility/src/api/quizQuestions.js
- packages/eligibility/src/components/Result.js
> Update Eligibility Form based on user feedback

- packages/eligibility/src/Eligibility.js
- packages/eligibility/src/api/quizQuestions.js
- packages/eligibility/src/components/AnswerOption.js
- packages/eligibility/src/components/FAQ.js
- packages/eligibility/src/components/Result.js
- packages/eligibility/src/index.css
> Add introductory page

- packages/eligibility/README.md
- packages/eligibility/src/components/Eligibility.js
- packages/eligibility/src/index.js
> Add documentation to Eligibility Form package

- packages/eligibility/README.md
- packages/eligibility/src/api/quizQuestions.js
- packages/eligibility/src/components/Eligibility.js
- packages/eligibility/src/components/Result.js
> Update Eligibility Form based on Feedback Round 2

- packages/eligibility/src/components/Eligibility.js
Fix #52 
This pull request combined with the changes made [here](https://github.com/lacabra/submission-digitalpublicgoods/pull/55), should resolve #52.
> Resolve issue in passing initial state to submission form

- .github/workflows/auto.yml
- package-lock.json
- packages/automation/index.js
- packages/roadmap/package-lock.json
- packages/roadmap/package.json
- packages/roadmap/src/components/Roadmap.js
- packages/roadmap/src/components/style.css
- packages/roadmap/src/index.css
- packages/roadmap/src/index.js
- scripts/moveFiles.bash
Add interactive roadmap at https://digitalpublicgoods/roadmap:
> BLD: add interactive roadmap

- packages/map/components/footer.js
- packages/map/components/infoComponent.js
- packages/map/components/mapComponent.js
- packages/map/components/searchBox.js
- packages/map/pages/index.js
- packages/map/styles/global.css
Implemented recommendations from [this issue](https://github.com/unicef/publicgoods-scripts/issues/68):
I will post new screenshots in the next comment.
@lacabra kindly review the changes.
Closes #68
> [Map] Improve map visualization

- packages/map/components/mapComponent.js
- packages/map/next.config.js
- packages/map/styles/global.css
> [Map] Fix images bug

- packages/automation/generate_nominees.js
Fix DPGAlliance/publicgoods-website#17, which was introduced in #113 while attempting to fix an earlier similar bug.
Cc: @prajectory
> BUG: fix DPGAlliance/publicgoods-website#17

- packages/registry/src/index.js
This PR:
- Removes the URL on the badge for DPGs in the registry list (`/registry`)
> removed URL from DPG badge in registry list

- packages/registry/src/index.js
Fixes https://github.com/DPGAlliance/publicgoods-candidates/issues/1348
There is some history as to why the DPGs mentioned did not show as they were part of the first DPGs to be put into the registry. More details on why this was the case by design would be in the issue link mentioned.
> Fix for hidden names of initial DPG's in registry

- packages/eligibility/README.md
- packages/eligibility/src/components/Eligibility.js
Changing links from the current submission form to the new web app to collect submissions.
> Updated eligibility form results link to new app

- packages/registry/src/index.js
A number of properties for a particular entry coming from the API were missing. This caused the registry table not to render. 
As such conditional code has to be written to handle these edge cases
> Added conditions for when json properties are missing

- packages/registry/src/index.js
This PR:
- Sorts DPGs on registry page in alphabetical order during the page build process
- Minor code cleanup
> Sort Registry in alphabetical order

- packages/registry/src/index.js
This PR fixes a number of issues mentioned in the links below
https://github.com/DPGAlliance/publicgoods-website/issues/21#event-8353576505
https://github.com/DPGAlliance/publicgoods-website/issues/22#event-8353592928 
and 
https://github.com/DPGAlliance/publicgoods-website/issues/23
> Registry-filter-patch

- packages/registry/src/index.js
> temp change to select all text

- .gitignore
- packages/automation/index.js
This PR fixes the breaking page build highlighted in #179 due to JSON structure changes.
> Fix for WebApp 2.0 API changes

- packages/registry/src/index.js
- updates logic to compute SDG filter class names on item elements
- ~~updates project setup instructions~~ (edit: moved to a separate PR)
> fix(registry): fixes filtering registry entries by SDG

- packages/community/index.html
- packages/community/index.js
Changes URL from Notion pilot to new GitHub Community repo
> Update community center URL

- packages/registry/src/index.js
Replaced the static DPG icon in ListItemBeta with dynamic SVG icons corresponding to different categories of listed items. A new function, getSVGIcon, was created for rendering SVG icons based on the categories. This enriches the visual presentation, provides contextual information, and enhances the user interface experience.
> Update SVG icon rendering in ListItemBeta
